name: workflow docker example
on:
  push:
    paths: 'hello-world-docker-action/**'
  workflow_dispatch:

jobs:
  RunDockerExample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
